[project]
name = "graph-visualization-backend"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
	"fastapi",
	"sqlalchemy",
	"uvicorn",
	"pydantic",
]
authors = [{name = "Atishaya Maharjan", email = "atishaya7777@gmail.com"}]
description = "Backend for graph visualization"
